# Week 8 (Tue) - Class Activities in CS 315

You are given the file `netflix_top10_countries.tsv` in the folder data, solve the following tasks using it.

**Table of Contents**

1. [Q1: Load the file](#q1)
2. [Q2: Show number of rows](#q2)
3. [Q3: Show column names](#q3)
4. [Q4: Show number of total countries](#q4)
5. [Q5: Show number of TV series](#q5)
6. [Q6: Number of TV series in South Korea](#q6)
7. [Q7: Total weeks of Squid Games in Italy ](#q7)
8. [Q8: Time frame for a given country](#q8)
9. [Q9: Is number of weeks in ranking equal?](#q9)
10. [Q10: Country with fewest weeks](#q10)

<a id="q1"></a>
### Q1: Load the file

In [1]:
import pandas as pd
url = "https://www.netflix.com/tudum/top10/data/all-weeks-countries.tsv"
df = pd.read_csv(url, sep = "\t")
df.head

<bound method NDFrame.head of        country_name country_iso2        week category  weekly_rank  \
0         Argentina           AR  2026-10-18    Films            1
1         Argentina           AR  2026-10-18    Films            2
2         Argentina           AR  2026-10-18    Films            3
3         Argentina           AR  2026-10-18    Films            4
4         Argentina           AR  2026-10-18    Films            5
...             ...          ...         ...      ...          ...
515915      Vietnam           VN  2021-07-04       TV            6
515916      Vietnam           VN  2021-07-04       TV            7
515917      Vietnam           VN  2021-07-04       TV            8
515918      Vietnam           VN  2021-07-04       TV            9
515919      Vietnam           VN  2021-07-04       TV           10

                       show_title                          season_title  \
0              Therapy Done Right                                   NaN
1                         Animals                                   NaN
2                  Anyone But You                                   NaN
3                      Doing Life                                   NaN
4       Ice Age: Collision Course                                   NaN
...                           ...                                   ...
515915                 Reply 1988                  Reply 1988: Season 1
515916              Nevertheless,         Nevertheless,: Limited Series
515917          Too Hot to Handle           Too Hot to Handle: Season 2
515918         Record of Ragnarok          Record of Ragnarok: Season 1
515919       Crash Landing on You  Crash Landing on You: Limited Series

        cumulative_weeks_in_top_10
0                                1
1                                2
2                                2
3                                3
4                                5
...                            ...
515915                           1
515916                           1
515917                           1
515918                           1
515919                           1

[515920 rows x 8 columns]>

<a id="q2"></a>
### Q2: Show number of rows

In [2]:
df.shape[0]

515920

<a id="q3"></a>
### Q3: Show column names

In [3]:
df.columns

Index(['country_name', 'country_iso2', 'week', 'category', 'weekly_rank',
       'show_title', 'season_title', 'cumulative_weeks_in_top_10'],
      dtype='str')

<a id="q4"></a>
### Q4: Show number of total countries

In [4]:
df['country_name'].nunique()

94

<a id="q5"></a>
### Q5: Show number of TV series

In [5]:
df[df["category"] == "TV"]["show_title"].nunique()

3607

<a id="q6"></a>
### Q6: Number of TV series in South Korea

In [6]:
df[(df["country_name"] == "South Korea") & (df["category"] == "TV")]["show_title"].nunique()

486

<a id="q7"></a>
### Q7: Total weeks of Squid Game in Italy

In [7]:
df[(df["country_name"] == "Italy") & (df["show_title"] == "Squid Game")]["week"].nunique()

29

<a id="q8"></a>
### Q8: Time frame for a given country

Write a function that given a country name prints out the start and end date of their rankings.

Once you have created the function, call it for a few countries to test it.

In [8]:
def show_timeframe(df, name):
    data = df[df["country_name"] == name]
    print(f"Netflix rankings for {name} exist between {data['week'].min()} and {data['week'].max()}.")

In [10]:
show_timeframe(df, "Russia")

Netflix rankings for Russia exist between 2021-07-04 and 2022-02-27.

<a id="q9"></a>
### Q9: Is number of weeks equal for each country?

The total number of weeks in the rankings is `len(df['week'].unique())`.

The total number of countries is `len(df['country_name'].unique())`.  

For every week, each country has 20 rows.   

If they all stayed the same number of weeks, then the product of these three weeks would be the same as the total number of rows.

In [11]:
df.groupby("country_name")["week"].nunique().nunique() == 1

False

We should have expected this to be `False` since we saw in Q8 that Russia stopped being in the rankings after it attacked Ukraine in February 2022.

<a id="q10"></a>
### Q10: Country with fewest weeks

Write a one-liner that will show the country with the fewest weeks in the Netflix rankings

In [12]:
df.groupby("country_name")["week"].nunique().reset_index(name="weekCnt").sort_values("weekCnt").head(1)

   country_name  weekCnt
70       Russia       35

### New Task: rank2score

In [ ]:
# Take a rank and return a score
def rank2score(rank):
    points = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1]
    return points[rank - 1]

df["score"] = df["weekly_rank"].apply(rank2score)

# display the useful columns
df[["country_name", "week", "weekly_rank", "score", "show_title", "cumulative_weeks_in_top_10"]].head(10)

,country_name,week,weekly_rank,score,show_title,cumulative_weeks_in_top_10
0,Argentina,2026-10-18,1,25,Therapy Done Right,1
1,Argentina,2026-10-18,2,18,Animals,2
2,Argentina,2026-10-18,3,15,Anyone But You,2
3,Argentina,2026-10-18,4,12,Doing Life,3
4,Argentina,2026-10-18,5,10,Ice Age: Collision Course,5
5,Argentina,2026-10-18,6,8,Corpse Bride,1
6,Argentina,2026-10-18,7,6,Acid,2
7,Argentina,2026-10-18,8,4,Ice Age: Dawn of the Dinosaurs,6
8,Argentina,2026-10-18,9,2,The Storm,1
9,Argentina,2026-10-18,10,1,The Equalizer 3,3

In [14]:
# reproduce the lovely runner table
(df[df["show_title"] == "Lovely Runner"]
   .sort_values("week")                        
   .groupby("country_name")
   .agg(total_score=("score", "sum"),
        total_weeks=("week", "nunique"),
        rankings_list=("weekly_rank", list))
   .reset_index()
   .sort_values("total_score", ascending=False))

   country_name  total_score  total_weeks          rankings_list
12      Vietnam           75            7  [5, 1, 4, 5, 6, 7, 8]
2     Indonesia           69            7  [5, 1, 4, 7, 6, 7, 9]
3      Malaysia           62            6     [4, 1, 3, 7, 9, 9]
6   Philippines           41            4           [5, 3, 5, 7]
4      Maldives           32            4          [6, 3, 6, 10]
9     Sri Lanka           32            4          [5, 3, 7, 10]
0    Bangladesh           30            3              [6, 4, 5]
1         India           26            3              [5, 4, 8]
7     Singapore           20            4           [9, 5, 7, 9]
11     Thailand           20            3              [5, 8, 7]
8   South Korea           18            3              [5, 7, 9]
10       Taiwan           10            2                 [8, 7]
5      Pakistan            6            1                    [7]

In [15]:
# Our project is about feminism in kdramas - picked The Glory as an example
(df[df["show_title"] == "The Glory"]
   .sort_values("week")                        
   .groupby("country_name")
   .agg(total_score=("score", "sum"),
        total_weeks=("week", "nunique"),
        rankings_list=("weekly_rank", list))
   .reset_index()
   .sort_values("total_score", ascending=False))

,country_name,total_score,total_weeks,rankings_list
81,Taiwan,352,23,"[2, 1, 1, 1, 1, 2, 6, 8, 7, 5, 1, 1, 1, 2, 2, ..."
29,Hong Kong,345,25,"[7, 1, 1, 1, 1, 3, 5, 7, 8, 10, 1, 1, 1, 1, 2,..."
90,Vietnam,312,21,"[3, 1, 1, 1, 1, 4, 6, 7, 8, 9, 1, 1, 1, 1, 2, ..."
76,South Korea,298,20,"[2, 1, 1, 1, 3, 5, 6, 8, 6, 5, 1, 1, 1, 1, 2, ..."
33,Indonesia,294,20,"[2, 1, 1, 1, 3, 3, 6, 8, 9, 8, 1, 1, 1, 2, 2, ..."
...,...,...,...,...
34,Ireland,10,1,[5]
31,Iceland,8,1,[6]
42,Latvia,8,1,[6]
77,Spain,4,1,[8]
74,Slovenia,2,1,[9]

In [16]:
# Example on "Extraordinary Attorney Woo"
(df[df["show_title"] == "Extraordinary Attorney Woo"]
   .sort_values("week")                        
   .groupby("country_name")
   .agg(total_score=("score", "sum"),
        total_weeks=("week", "nunique"),
        rankings_list=("weekly_rank", list))
   .reset_index()
   .sort_values("total_score", ascending=False))

,country_name,total_score,total_weeks,rankings_list
22,Japan,370,25,"[3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, ..."
49,Taiwan,308,17,"[9, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 4, 4, 6, ..."
18,Hong Kong,295,18,"[10, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 5, 7,..."
45,Singapore,284,17,"[10, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 7, 6, 7,..."
46,South Korea,268,16,"[2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 5, 7, 10, 10..."
20,Indonesia,262,15,"[3, 1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 4, 5, 8, 10]"
56,Vietnam,239,13,"[1, 1, 1, 1, 1, 1, 1, 2, 2, 6, 5, 7, 8]"
39,Peru,236,16,"[7, 3, 2, 2, 1, 1, 1, 1, 2, 3, 5, 4, 7, 5, 7, 9]"
50,Thailand,234,24,"[9, 3, 1, 1, 1, 1, 3, 1, 3, 5, 8, 9, 7, 6, 5, ..."
27,Malaysia,231,15,"[10, 4, 1, 1, 1, 1, 1, 1, 2, 3, 4, 6, 7, 6, 10]"
4,Bolivia,229,14,"[5, 2, 1, 1, 1, 1, 1, 2, 4, 4, 5, 6, 6, 6]"
40,Philippines,209,13,"[5, 2, 1, 1, 1, 1, 1, 3, 3, 4, 7, 8, 8]"
30,Mexico,162,14,"[8, 2, 2, 2, 1, 2, 2, 3, 6, 6, 8, 7, 10, 10]"
7,Chile,159,14,"[9, 3, 3, 3, 2, 1, 1, 2, 5, 6, 8, 9, 10, 10]"
5,Brazil,154,13,"[7, 4, 3, 2, 2, 1, 2, 4, 6, 8, 7, 7, 7]"
35,Oman,128,9,"[4, 2, 1, 3, 3, 2, 2, 7, 10]"
42,Qatar,128,10,"[10, 4, 2, 1, 2, 3, 2, 4, 6, 10]"
13,El Salvador,124,10,"[9, 5, 4, 2, 2, 2, 1, 3, 8, 9]"
28,Maldives,123,9,"[3, 3, 1, 2, 3, 3, 4, 8, 8]"
44,Saudi Arabia,121,9,"[4, 2, 1, 3, 2, 2, 5, 8, 10]"
52,United Arab Emirates,119,8,"[4, 2, 1, 2, 4, 2, 5, 7]"
3,Bangladesh,114,8,"[8, 4, 1, 1, 3, 3, 5, 6]"
48,Sri Lanka,114,10,"[10, 5, 4, 1, 2, 3, 3, 5, 7, 9]"
55,Venezuela,108,11,"[8, 5, 2, 2, 1, 2, 6, 9, 9, 9, 10]"
2,Bahrain,106,8,"[4, 3, 1, 3, 4, 3, 5, 9]"
37,Panama,105,9,"[6, 5, 4, 2, 2, 1, 4, 10, 10]"
33,Nicaragua,105,7,"[6, 4, 3, 2, 3, 1, 4]"
38,Paraguay,98,7,"[5, 3, 4, 2, 3, 2, 5]"
11,Ecuador,96,9,"[10, 4, 4, 3, 3, 4, 2, 5, 10]"
16,Guatemala,95,8,"[10, 6, 5, 3, 2, 3, 2, 5]"
17,Honduras,95,9,"[9, 7, 5, 3, 2, 3, 2, 5, 10]"
25,Kuwait,94,8,"[5, 4, 1, 4, 4, 3, 8, 8]"
9,Costa Rica,87,8,"[9, 7, 4, 2, 3, 2, 4, 8]"
10,Dominican Republic,80,9,"[7, 5, 4, 4, 3, 3, 6, 10, 10]"
8,Colombia,75,9,"[7, 5, 4, 3, 2, 5, 10, 9, 10]"
23,Jordan,74,8,"[8, 3, 3, 5, 7, 5, 6, 7]"
19,India,72,7,"[9, 4, 3, 5, 3, 5, 6]"
31,Morocco,68,8,"[10, 5, 6, 6, 4, 4, 3, 9]"
34,Nigeria,64,7,"[7, 5, 3, 4, 4, 6, 10]"
21,Israel,61,7,"[6, 10, 6, 3, 5, 3, 8]"
32,New Zealand,47,7,"[7, 5, 8, 5, 4, 8, 10]"
12,Egypt,43,7,"[9, 7, 3, 6, 9, 6, 9]"
0,Argentina,38,5,"[6, 6, 6, 4, 9]"
54,Uruguay,25,5,"[9, 9, 6, 4, 10]"
1,Australia,25,5,"[10, 7, 8, 9, 4]"
41,Portugal,24,3,"[7, 6, 5]"
36,Pakistan,20,4,"[10, 10, 6, 5]"
51,Turkey,16,4,"[7, 7, 9, 9]"
24,Kenya,13,4,"[10, 9, 8, 7]"
29,Mauritius,12,4,"[9, 9, 7, 9]"
47,Spain,11,2,"[10, 5]"
6,Canada,6,1,[7]
15,Greece,4,3,"[10, 10, 9]"
26,Lebanon,4,3,"[10, 9, 10]"
53,United States,3,2,"[10, 9]"
14,Finland,2,1,[9]
43,Romania,2,2,"[10, 10]"